FROM node:22-alpine

WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]