services:
  backend-synkro:
    image: ${DOCKERHUB_USERNAME}/synkro-backend:latest
    container_name: symfony_app
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-synkro:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8
      JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      MAILER_DSN: ${MAILER_DSN}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
    depends_on:
      - postgres-synkro
    networks:
      - synkronet-synkro

  websocket-synkro:
    image: ${DOCKERHUB_USERNAME}/synkro-websocket:latest
    container_name: websocket_server
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - synkronet-synkro

  frontend-synkro:
    image: ${DOCKERHUB_USERNAME}/synkro-frontend:latest
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend-synkro
      - websocket-synkro
    networks:
      - synkronet-synkro

  mailpit-synkro:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    networks:
      - synkronet-synkro

  postgres-synkro:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - synkronet-synkro

  # L'outil qui permet la mise à jour automatique sans toucher au VPS
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    restart: always

volumes:
  postgres_data:

networks:
  synkronet-synkro:
    driver: bridge
