services:
  backend-synkro:
    build:
      context: ./backend
      target: dev
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD_ENC}@postgres-synkro:${PORT_POSTGRES_2}/${POSTGRES_DB}?serverVersion=16&charset=utf8
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres-synkro
    ports:
      - ${PORT_BACKEND}
    networks:
      - synkronet-synkro

  websocket-synkro:
    build:
      context: ./server
      target: dev
    container_name: websocket_server
    restart: unless-stopped
    ports:
      - ${PORT_WEBSOCKET}
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - synkronet-synkro

  frontend-synkro:
    build:
      context: ./frontend
      target: dev
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - ${PORT_FRONTEND_DEV:-5173:5173}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_TARGET=http://backend-synkro:8000
    depends_on:
      - backend-synkro
      - websocket-synkro
    networks:
      - synkronet-synkro

  mailpit-synkro:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - synkronet-synkro

  postgres-synkro:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - ${PORT_POSTGRES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - synkronet-synkro

volumes:
  postgres_data:

networks:
  synkronet-synkro:
    driver: bridge