<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260205140508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add kanban_column table, migrate task status to column_id, add task type';
    }

    public function up(Schema $schema): void
    {
        // Step 1: Create kanban_column table
        $this->addSql('CREATE TABLE kanban_column (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(50) NOT NULL, position INT NOT NULL, room_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_kanban_column_room ON kanban_column (room_id)');
        $this->addSql('ALTER TABLE kanban_column ADD CONSTRAINT FK_157CF28654177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Step 2: Seed default columns for every existing room
        $this->addSql("INSERT INTO kanban_column (room_id, name, color, position) SELECT id, 'À faire', 'bg-slate-500', 0 FROM room");
        $this->addSql("INSERT INTO kanban_column (room_id, name, color, position) SELECT id, 'En cours', 'bg-blue-500', 1 FROM room");
        $this->addSql("INSERT INTO kanban_column (room_id, name, color, position) SELECT id, 'Terminé', 'bg-green-500', 2 FROM room");

        // Step 3: Add column_id and type as NULLABLE first
        $this->addSql('ALTER TABLE task ADD column_id INT DEFAULT NULL');
        $this->addSql("ALTER TABLE task ADD type VARCHAR(20) DEFAULT 'active'");

        // Step 4: Migrate existing tasks from status to column_id
        $this->addSql("UPDATE task t SET column_id = (
            SELECT kc.id FROM kanban_column kc
            WHERE kc.room_id = t.room_id
            AND kc.name = CASE t.status
                WHEN 'todo' THEN 'À faire'
                WHEN 'in_progress' THEN 'En cours'
                WHEN 'done' THEN 'Terminé'
            END
        )");

        // Step 5: Set type for all existing tasks
        $this->addSql("UPDATE task SET type = 'active' WHERE type IS NULL");

        // Step 6: Now make columns NOT NULL
        $this->addSql('ALTER TABLE task ALTER COLUMN column_id SET NOT NULL');
        $this->addSql('ALTER TABLE task ALTER COLUMN type SET NOT NULL');

        // Step 7: Add FK, drop old column, create indexes
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25BE8E8ED5 FOREIGN KEY (column_id) REFERENCES kanban_column (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX IF EXISTS idx_task_status');
        $this->addSql('ALTER TABLE task DROP COLUMN status');
        $this->addSql('CREATE INDEX idx_task_column ON task (column_id)');
        $this->addSql('CREATE INDEX idx_task_type ON task (type)');

        $this->addSql('ALTER TABLE module_room ALTER display_order DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25BE8E8ED5');
        $this->addSql('DROP INDEX idx_task_column');
        $this->addSql('DROP INDEX idx_task_type');

        // Re-add status column
        $this->addSql("ALTER TABLE task ADD status VARCHAR(50) NOT NULL DEFAULT 'todo'");

        // Migrate back
        $this->addSql("UPDATE task t SET status = CASE
            (SELECT kc.name FROM kanban_column kc WHERE kc.id = t.column_id)
            WHEN 'À faire' THEN 'todo'
            WHEN 'En cours' THEN 'in_progress'
            WHEN 'Terminé' THEN 'done'
            ELSE 'todo'
        END");

        $this->addSql('ALTER TABLE task DROP COLUMN type');
        $this->addSql('ALTER TABLE task DROP COLUMN column_id');
        $this->addSql('CREATE INDEX idx_task_status ON task (status)');

        $this->addSql('ALTER TABLE kanban_column DROP CONSTRAINT FK_157CF28654177093');
        $this->addSql('DROP TABLE kanban_column');

        $this->addSql('ALTER TABLE module_room ALTER display_order SET DEFAULT 0');
    }
}
