<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260105080711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        // Create user table FIRST (other tables depend on it)
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, entreprise_id INT DEFAULT NULL, team_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, event_type VARCHAR(20) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_all_day BOOLEAN NOT NULL, recurrence VARCHAR(100) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, is_private BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT DEFAULT NULL, user_id INT NOT NULL, entreprise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57FA09C954177093 ON calendar_event (room_id)');
        $this->addSql('CREATE INDEX idx_event_entreprise ON calendar_event (entreprise_id)');
        $this->addSql('CREATE INDEX idx_event_user ON calendar_event (user_id)');
        $this->addSql('CREATE INDEX idx_event_dates ON calendar_event (start_date, end_date)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content_markdown TEXT DEFAULT NULL, yjs_state BYTEA DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8698A7654177093 ON document (room_id)');
        $this->addSql('CREATE TABLE entreprise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D19FA60A7A91E0B ON entreprise (domain)');
        $this->addSql('CREATE TABLE file_resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC17B8BA76ED395 ON file_resource (user_id)');
        $this->addSql('CREATE INDEX idx_file_room ON file_resource (room_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FA76ED395 ON message (user_id)');
        $this->addSql('CREATE INDEX idx_message_room ON message (room_id)');
        $this->addSql('CREATE INDEX idx_message_created ON message (created_at)');
        $this->addSql('CREATE TABLE module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C24262877153098 ON module (code)');
        $this->addSql('CREATE TABLE module_room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, config_json JSON DEFAULT NULL, room_id INT NOT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8A3149754177093 ON module_room (room_id)');
        $this->addSql('CREATE INDEX IDX_C8A31497AFC2B591 ON module_room (module_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_room_module ON module_room (room_id, module_id)');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_temporary BOOLEAN NOT NULL, visibility VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creator_id INT NOT NULL, entreprise_id INT NOT NULL, template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_729F519B61220EA6 ON room (creator_id)');
        $this->addSql('CREATE INDEX IDX_729F519BA4AEAFEA ON room (entreprise_id)');
        $this->addSql('CREATE INDEX IDX_729F519B5DA0FB8 ON room (template_id)');
        $this->addSql('CREATE TABLE room_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, is_default BOOLEAN NOT NULL, creator_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3786DF4761220EA6 ON room_template (creator_id)');
        $this->addSql('CREATE INDEX IDX_3786DF47A4AEAFEA ON room_template (entreprise_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25F4BD7827 ON task (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_task_room ON task (room_id)');
        $this->addSql('CREATE INDEX idx_task_status ON task (status)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, entreprise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61FA4AEAFEA ON team (entreprise_id)');
        $this->addSql('CREATE TABLE team_room_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, room_id INT NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F7E5F8C854177093 ON team_room_permission (room_id)');
        $this->addSql('CREATE INDEX IDX_F7E5F8C8296CD8AE ON team_room_permission (team_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_team_room ON team_room_permission (team_id, room_id)');
        $this->addSql('CREATE TABLE template_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, template_id INT NOT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC2FDA5DA0FB8 ON template_module (template_id)');
        $this->addSql('CREATE INDEX IDX_7CC2FDAAFC2B591 ON template_module (module_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_template_module ON template_module (template_id, module_id)');
        $this->addSql('CREATE TABLE user_room_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, room_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C6678E3954177093 ON user_room_permission (room_id)');
        $this->addSql('CREATE INDEX IDX_C6678E39A76ED395 ON user_room_permission (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_room ON user_room_permission (user_id, room_id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C954177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7654177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file_resource ADD CONSTRAINT FK_DC17B8B54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file_resource ADD CONSTRAINT FK_DC17B8BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_room ADD CONSTRAINT FK_C8A3149754177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_room ADD CONSTRAINT FK_C8A31497AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B61220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519BA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B5DA0FB8 FOREIGN KEY (template_id) REFERENCES room_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE room_template ADD CONSTRAINT FK_3786DF4761220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE room_template ADD CONSTRAINT FK_3786DF47A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2554177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_room_permission ADD CONSTRAINT FK_F7E5F8C854177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_room_permission ADD CONSTRAINT FK_F7E5F8C8296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE template_module ADD CONSTRAINT FK_7CC2FDA5DA0FB8 FOREIGN KEY (template_id) REFERENCES room_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE template_module ADD CONSTRAINT FK_7CC2FDAAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_room_permission ADD CONSTRAINT FK_C6678E3954177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_room_permission ADD CONSTRAINT FK_C6678E39A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        // User table constraints and indexes (table already created above)
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649A4AEAFEA ON "user" (entreprise_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649296CD8AE ON "user" (team_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C954177093');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9A76ED395');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9A4AEAFEA');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7654177093');
        $this->addSql('ALTER TABLE file_resource DROP CONSTRAINT FK_DC17B8B54177093');
        $this->addSql('ALTER TABLE file_resource DROP CONSTRAINT FK_DC17B8BA76ED395');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F54177093');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FA76ED395');
        $this->addSql('ALTER TABLE module_room DROP CONSTRAINT FK_C8A3149754177093');
        $this->addSql('ALTER TABLE module_room DROP CONSTRAINT FK_C8A31497AFC2B591');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B61220EA6');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519BA4AEAFEA');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B5DA0FB8');
        $this->addSql('ALTER TABLE room_template DROP CONSTRAINT FK_3786DF4761220EA6');
        $this->addSql('ALTER TABLE room_template DROP CONSTRAINT FK_3786DF47A4AEAFEA');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2554177093');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25F4BD7827');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FA4AEAFEA');
        $this->addSql('ALTER TABLE team_room_permission DROP CONSTRAINT FK_F7E5F8C854177093');
        $this->addSql('ALTER TABLE team_room_permission DROP CONSTRAINT FK_F7E5F8C8296CD8AE');
        $this->addSql('ALTER TABLE template_module DROP CONSTRAINT FK_7CC2FDA5DA0FB8');
        $this->addSql('ALTER TABLE template_module DROP CONSTRAINT FK_7CC2FDAAFC2B591');
        $this->addSql('ALTER TABLE user_room_permission DROP CONSTRAINT FK_C6678E3954177093');
        $this->addSql('ALTER TABLE user_room_permission DROP CONSTRAINT FK_C6678E39A76ED395');
        $this->addSql('DROP TABLE calendar_event');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE file_resource');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE module_room');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE room_template');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_room_permission');
        $this->addSql('DROP TABLE template_module');
        $this->addSql('DROP TABLE user_room_permission');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649A4AEAFEA');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649296CD8AE');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
        $this->addSql('DROP INDEX IDX_8D93D649A4AEAFEA');
        $this->addSql('DROP INDEX IDX_8D93D649296CD8AE');
        $this->addSql('DROP TABLE "user"');
    }
}
