<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration for creating the whiteboard table
 */
final class Version20260108100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create whiteboard table for collaborative whiteboard module';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE whiteboard (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, yjs_state BYTEA DEFAULT NULL, strokes JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E5D972654177093 ON whiteboard (room_id)');
        $this->addSql('ALTER TABLE whiteboard ADD CONSTRAINT FK_4E5D972654177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE whiteboard DROP CONSTRAINT FK_4E5D972654177093');
        $this->addSql('DROP TABLE whiteboard');
    }
}
