<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260107084914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE calendar_event_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E3F350471F7E88B ON calendar_event_participant (event_id)');
        $this->addSql('CREATE INDEX IDX_2E3F3504A76ED395 ON calendar_event_participant (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_event_participant ON calendar_event_participant (event_id, user_id)');
        $this->addSql('ALTER TABLE calendar_event_participant ADD CONSTRAINT FK_2E3F350471F7E88B FOREIGN KEY (event_id) REFERENCES calendar_event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event_participant ADD CONSTRAINT FK_2E3F3504A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE calendar_event_participant DROP CONSTRAINT FK_2E3F350471F7E88B');
        $this->addSql('ALTER TABLE calendar_event_participant DROP CONSTRAINT FK_2E3F3504A76ED395');
        $this->addSql('DROP TABLE calendar_event_participant');
    }
}
