apiVersion: v1
kind: ConfigMap
metadata:
  name: synkro-config
  namespace: synkro
data:
  APP_ENV: "prod"
  CORS_ALLOW_ORIGIN: "^https?://.*$"
  GOOGLE_REDIRECT_URI: "http://195.15.195.73/auth/google/callback"
  APP_FRONTEND_URL: "http://195.15.195.73"
  DEFAULT_URI: "http://195.15.195.73"
