[vps]
# Tant que la transition SSH 22->2222 n'est pas validée, ansible_port=22.
# Après le premier site.yml :
#   1) tester  : ssh -p 2222 sysadmin@152.228.131.12
#   2) changer ici en ansible_port=2222
#   3) relancer : ansible-playbook site.yml -e ssh_close_old_port=true
152.228.131.12 ansible_user=sysadmin ansible_port=22 ansible_ssh_private_key_file=~/.ssh/id_ed25519